stages:
    - test
    - deploy

test-job1:
    stage: test
    script:
        - echo "Hello, $GITLAB_USER_LOGIN!"

job-deploy:
    stage: deploy
    image: docker/compose:latest
    services:
        - docker:dind
    script:
        - docker info
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        - docker-compose build
        - docker-compose push
