variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    NODE_OPTIONS: --max_old_space_size=4096

stages:
    - test
    - deploy

test-job1:
    stage: test
    script:
        - echo "Hello, $GITLAB_USER_LOGIN!"

pages:
  stage: deploy
  script:
    - cp -r docs/. public
  artifacts:
    paths:
    - public
  only:
    - master

job-deploy:
    stage: deploy
    image: docker/compose:1.25.0-rc2
    services:
        - docker:19.03.12-dind
    script:
        # - docker info
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        - docker-compose build
        - docker-compose push
