production:
    stage: deploy
    tag: platform
    image: docker/compose:latest
    services:
        - docker:dind
    before_script:
        - docker info
    script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        - docker-compose build
        - docker-compose push
