version: "3.3"
services:
  db:
    image: postgres:12
    env_file: .env.database-only
    ports:
    - 5656:5432
    volumes:
      - database:/var/lib/postgresql
volumes:
    files: {}
    database: {}