version: "3.3"
services:
  backend:
    image: registry.gitlab.com/cassiano.pvianna/ct-puzzle-platform/backend:1.0
    env_file: .env.prod
    build: 
        context: backend
    command: npm start
    ports:
    - 3010:${BACKEND_PORT:-3001}
    depends_on:
    - db
  frontend:
    image: registry.gitlab.com/cassiano.pvianna/ct-puzzle-platform/frontend:1.0
    env_file: .env.prod
    build: 
        context: frontend
        args: 
            API_URL: $API_URL
            NODE_ENV: ${NODE_ENV:-production}
    ports:
    - 3020:${NUXT_PORT:-3002}
    command: npm start
    depends_on:
    - backend
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_DB: $DATABASE_NAME
    ports:
    - 5656:5432
