version: "3.3"
services:
  backend:
    image: ct-puzzle-platform-backend:1.0
    env_file: .env.prod.local
    build: 
        context: backend
    command: npm start
    ports:
    - 3010:${BACKEND_PORT:-3001}
    depends_on:
    - db
  frontend:
    image: ct-puzzle-platform-frontend:1.0
    env_file: .env.prod.local
    build: 
        context: frontend
        args: 
            API_URL: $API_URL
            NODE_ENV: ${NODE_ENV:-production}
    ports:
    - 3020:${NUXT_PORT:-3002}
    command: npm start
    depends_on:
    - backend
  db:
    image: postgres:12
    env_file: .env.prod.local
    ports:
    - 5656:5432